FIND_PATH(VORBISFILE_INCLUDE_DIR NAMES vorbis/vorbisfile.h)
MARK_AS_ADVANCED(VORBISFILE_INCLUDE_DIR)
 
FIND_LIBRARY(VORBISFILE_LIBRARIES NAMES
  vorbisfile
  libvorbisfile
  vorbisfilelib)
MARK_AS_ADVANCED(VORBISFILE_LIBRARIES)
 
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS (VorbisFile DEFAULT_MSG
                                   VORBISFILE_LIBRARIES VORBISFILE_INCLUDE_DIR)
