dist: bionic
language: c
compiler:
  - clang
  - gcc

install:
  - sudo apt-get -y install cmake libglu1-mesa-dev libopenal-dev libpng++-dev
  - sudo apt-get -y install libjpeg-dev libjsoncpp-dev libvorbis-dev

before_script:
  - mkdir build && cd build
  - cmake $TRAVIS_BUILD_DIR

script:
  - make
  - sudo make install
